/**
 * Official HS chapter titles (abbreviated WCO wording) for hierarchical retrieval.
 * Used because tariff.json contains national lines only.
 */
export const CHAPTER_TITLES: Record<string, string> = {
  "01": "Live animals",
  "02": "Meat and edible meat offal",
  "03": "Fish and crustaceans",
  "04": "Dairy produce; birds' eggs; natural honey",
  "05": "Products of animal origin, nes",
  "06": "Live trees and other plants",
  "07": "Edible vegetables",
  "08": "Edible fruit and nuts",
  "09": "Coffee, tea, mate and spices",
  "10": "Cereals",
  "11": "Products of the milling industry",
  "12": "Oil seeds and oleaginous fruits",
  "13": "Lac; gums, resins",
  "14": "Vegetable plaiting materials",
  "15": "Animal or vegetable fats and oils",
  "16": "Preparations of meat, fish etc.",
  "17": "Sugars and sugar confectionery",
  "18": "Cocoa and cocoa preparations",
  "19": "Preparations of cereals, flour, starch or milk",
  "20": "Preparations of vegetables, fruit, nuts",
  "21": "Miscellaneous edible preparations",
  "22": "Beverages, spirits and vinegar",
  "23": "Residues and waste from the food industries",
  "24": "Tobacco",
  "25": "Salt; sulphur; earths and stone",
  "26": "Ores, slag and ash",
  "27": "Mineral fuels",
  "28": "Inorganic chemicals",
  "29": "Organic chemicals",
  "30": "Pharmaceutical products",
  "31": "Fertilisers",
  "32": "Tanning or dyeing extracts; paints",
  "33": "Essential oils; perfumery, cosmetic",
  "34": "Soap; washing preparations; polishing preparations",
  "35": "Albuminoidal substances; glues; enzymes",
  "36": "Explosives; pyrotechnic products",
  "37": "Photographic or cinematographic goods",
  "38": "Miscellaneous chemical products",
  "39": "Plastics and articles thereof",
  "40": "Rubber and articles thereof",
  "41": "Raw hides and skins",
  "42": "Articles of leather",
  "43": "Furskins",
  "44": "Wood and articles of wood",
  "45": "Cork",
  "46": "Manufactures of straw",
  "47": "Pulp of wood",
  "48": "Paper and paperboard",
  "49": "Printed books, newspapers",
  "50": "Silk",
  "51": "Wool",
  "52": "Cotton",
  "53": "Other vegetable textile fibres",
  "54": "Man-made filaments",
  "55": "Man-made staple fibres",
  "56": "Wadding, felt and nonwovens",
  "57": "Carpets",
  "58": "Special woven fabrics",
  "59": "Impregnated, coated textile fabrics",
  "60": "Knitted or crocheted fabrics",
  "61": "Apparel, knitted",
  "62": "Apparel, not knitted",
  "63": "Other made up textile articles; sets; worn clothing",
  "64": "Footwear",
  "65": "Headgear and parts thereof",
  "66": "Umbrellas",
  "67": "Prepared feathers",
  "68": "Articles of stone, plaster, cement",
  "69": "Ceramic products",
  "70": "Glass and glassware",
  "71": "Precious metals and jewellery",
  "72": "Iron and steel",
  "73": "Articles of iron or steel",
  "74": "Copper and articles thereof",
  "75": "Nickel",
  "76": "Aluminium",
  "78": "Lead",
  "79": "Zinc",
  "80": "Tin",
  "81": "Other base metals",
  "82": "Tools, implements, cutlery",
  "83": "Miscellaneous articles of base metal",
  "84": "Nuclear reactors, boilers, machinery",
  "85": "Electrical machinery and equipment",
  "86": "Railway locomotives",
  "87": "Vehicles other than railway",
  "88": "Aircraft",
  "89": "Ships",
  "90": "Optical, medical instruments",
  "91": "Clocks and watches",
  "92": "Musical instruments",
  "93": "Arms and ammunition",
  "94": "Furniture; bedding; lamps",
  "95": "Toys, games and sports",
  "96": "Miscellaneous manufactured articles",
  "97": "Works of art",
};

export function chapterTitle(chapter: string): string {
  const ch = chapter.padStart(2, "0");
  return CHAPTER_TITLES[ch] || `Chapter ${ch}`;
}
